function immune_cell_MIET_biexp_report(out, outputDir)
%IMMUNE_CELL_MIET_BIEXP_REPORT Print and write a scalar summary of the fit.
%
% The soft-constraint diagnostics are the point of this summary. If the fitted
% tau1 sits at the edge of the prior across most pixels, the prior is fighting
% the data and its centre or width is wrong - that has to be visible rather than
% buried in a map.

    maps = out.maps;
    valid = isfinite(maps.tau1Ns);
    pull = maps.slbPullSigma(valid);
    tau2 = maps.tau2Ns(valid);
    f2 = maps.photonFraction2(valid);
    bg = maps.backgroundFraction(valid);
    dev = maps.reducedDeviance(valid);

    fprintf('\n  RESULT: %d pixel(s) fitted\n', nnz(valid));
    fprintf('      tau1 (SLB, soft)   median %.4f ns   prior centre %.4f\n', ...
        median(maps.tau1Ns(valid)), out.opts.slbTauNs);
    fprintf(['      prior pull         median %+.2f sigma, |pull| > 1.8 in ' ...
        '%.1f%% of pixels\n'], median(pull), ...
        100 * mean(abs(pull) > 1.8));
    if mean(abs(pull) > 1.8) > 0.5
        fprintf(['      WARNING: most pixels are pinned at the edge of the ' ...
            'prior, so the prior is\n      fighting the data. Revisit ' ...
            'slbTauNs or widen slbSigmaNs.\n']);
    end
    fprintf('      tau2 (free)        median %.3f ns, IQR [%.3f %.3f]\n', ...
        median(tau2), quantileLocalBiexp(tau2, 0.25), ...
        quantileLocalBiexp(tau2, 0.75));
    fprintf('      photon share tau2  median %.3f, IQR [%.3f %.3f]\n', ...
        median(f2), quantileLocalBiexp(f2, 0.25), ...
        quantileLocalBiexp(f2, 0.75));
    fprintf('      background share   median %.4f of the pixel photons\n', ...
        median(bg));
    fprintf('      reduced deviance   median %.3f, 90th pct %.3f\n', ...
        median(dev), quantileLocalBiexp(dev, 0.90));

    rows = struct('pixelsFitted', nnz(valid), ...
        'slbPriorCentreNs', out.opts.slbTauNs, ...
        'slbPriorSigmaNs', out.opts.slbSigmaNs, ...
        'tau1MedianNs', median(maps.tau1Ns(valid)), ...
        'priorPullMedianSigma', median(pull), ...
        'priorPinnedFraction', mean(abs(pull) > 1.8), ...
        'tau2MedianNs', median(tau2), ...
        'tau2Q1Ns', quantileLocalBiexp(tau2, 0.25), ...
        'tau2Q3Ns', quantileLocalBiexp(tau2, 0.75), ...
        'photonShare2Median', median(f2), ...
        'backgroundShareMedian', median(bg), ...
        'reducedDevianceMedian', median(dev), ...
        'reducedDevianceP90', quantileLocalBiexp(dev, 0.90), ...
        'binSize', out.opts.binSize, ...
        'elapsedSeconds', out.elapsedSeconds);
    csvFile = fullfile(outputDir, 'biexp_slb_summary.csv');
    writetable(struct2table(rows), csvFile);
    fprintf('  wrote %s\n', csvFile);
end
