function correction = immune_cell_MIET_correct_long_lifetime_bias( ...
        reportedLifetimeNs, slbPhotonCount, longPhotonCount, ...
        calibrationSource, cfg)
%IMMUNE_CELL_MIET_CORRECT_LONG_LIFETIME_BIAS Conservative inverse calibration.
%
% correction = immune_cell_MIET_correct_long_lifetime_bias( ...
%     reportedLifetimeNs, slbPhotonCount, longPhotonCount, ...
%     calibrationSource, cfg)
%
% Inverts the Monte-Carlo forward response generated by
% immune_cell_MIET_long_lifetime_bias. The three input arrays must have the
% same size. reportedLifetimeNs is the posterior-mean longer lifetime,
% slbPhotonCount is the outside-calibrated SLB prior mean, and
% longPhotonCount is the posterior-expected longer-component photon count.
%
% The raw map is never overwritten. correctedLifetimeNs contains values only
% where the simulated mean response is monotonic and sufficiently sensitive.
% candidateCorrectedLifetimeNs retains the inverse solution for diagnosis,
% including candidates rejected by the reliability gates.
%
% calibrationSource may be the long_lifetime_bias_analysis.mat filename, its
% saved analysis struct, or its summary table. Only slbPriorScale == 1 is used.
%
% Important cfg fields (all optional)
%   minForwardSlope                    0.25 reported ns / true ns
%   minDisplaySelectionRate            0.80
%   maxEmpiricalStdNs                   0.25
%   maxStdToLifetimeContrast            0.50
%   maxRelativeCorrection               0.35
%   maxCurveMonotonicAdjustmentNs        0.05
%   tauSlbNs                            [] (read from calibration)
%   batchSize                           50000 pixels
%
% Count handling is deliberately asymmetric. SLB counts below the simulated
% range and long counts above it are clamped conservatively. Long counts below
% the simulated range or SLB counts above it are rejected because extrapolation
% in those directions could conceal rather than bound the low-count bias.

    if nargin < 5 || isempty(cfg)
        cfg = struct();
    end
    cfg = fillDefaults(cfg);
    [reportedLifetimeNs, slbPhotonCount, longPhotonCount, outputSize] = ...
        validateMaps(reportedLifetimeNs, slbPhotonCount, longPhotonCount);
    calibration = loadCalibration(calibrationSource, cfg);

    pixelCount = numel(reportedLifetimeNs);
    candidate = nan(pixelCount, 1);
    corrected = nan(pixelCount, 1);
    estimatedBias = nan(pixelCount, 1);
    appliedCorrection = nan(pixelCount, 1);
    forwardSlope = nan(pixelCount, 1);
    predictedSelection = nan(pixelCount, 1);
    predictedStd = nan(pixelCount, 1);
    stdToContrast = nan(pixelCount, 1);
    curveAdjustment = nan(pixelCount, 1);
    reasonCode = zeros(pixelCount, 1, 'uint8');

    validInput = isfinite(reportedLifetimeNs) & reportedLifetimeNs > 0 & ...
        isfinite(slbPhotonCount) & slbPhotonCount > 0 & ...
        isfinite(longPhotonCount) & longPhotonCount > 0;
    reasonCode(validInput) = uint8(1);

    slbTooHigh = validInput & slbPhotonCount > calibration.slbPhotonAxis(end);
    longTooLow = validInput & longPhotonCount < calibration.longPhotonAxis(1);
    reasonCode(slbTooHigh) = uint8(3);
    reasonCode(longTooLow) = uint8(2);
    eligibleCount = validInput & ~slbTooHigh & ~longTooLow;

    slbForCalibration = min(max(slbPhotonCount, ...
        calibration.slbPhotonAxis(1)), calibration.slbPhotonAxis(end));
    longForCalibration = min(max(longPhotonCount, ...
        calibration.longPhotonAxis(1)), calibration.longPhotonAxis(end));
    conservativelyClamped = eligibleCount & ( ...
        slbPhotonCount < calibration.slbPhotonAxis(1) | ...
        longPhotonCount > calibration.longPhotonAxis(end));

    eligibleIndices = find(eligibleCount);
    for first = 1:cfg.batchSize:numel(eligibleIndices)
        localIndices = eligibleIndices(first:min( ...
            first + cfg.batchSize - 1, numel(eligibleIndices)));
        local = invertBatch(reportedLifetimeNs(localIndices), ...
            slbForCalibration(localIndices), ...
            longForCalibration(localIndices), calibration, cfg);
        candidate(localIndices) = local.candidate;
        forwardSlope(localIndices) = local.forwardSlope;
        predictedSelection(localIndices) = local.predictedSelection;
        predictedStd(localIndices) = local.predictedStd;
        stdToContrast(localIndices) = local.stdToContrast;
        curveAdjustment(localIndices) = local.curveAdjustment;
        reasonCode(localIndices) = local.reasonCode;
    end

    reliable = reasonCode == 1 & isfinite(candidate);
    corrected(reliable) = candidate(reliable);
    estimatedBias(isfinite(candidate)) = ...
        reportedLifetimeNs(isfinite(candidate)) - candidate(isfinite(candidate));
    appliedCorrection(isfinite(candidate)) = -estimatedBias(isfinite(candidate));

    correction = struct();
    correction.method = ['monotonic inverse Monte-Carlo calibration; raw values ' ...
        'retained; non-identifiable conditions rejected'];
    correction.rawLifetimeNs = reshape(single(reportedLifetimeNs), outputSize);
    correction.candidateCorrectedLifetimeNs = reshape(single(candidate), outputSize);
    correction.correctedLifetimeNs = reshape(single(corrected), outputSize);
    correction.estimatedEstimatorBiasNs = reshape(single(estimatedBias), outputSize);
    correction.appliedCorrectionNs = reshape(single(appliedCorrection), outputSize);
    correction.forwardSlope = reshape(single(forwardSlope), outputSize);
    correction.predictedDisplaySelectionRate = ...
        reshape(single(predictedSelection), outputSize);
    correction.predictedEmpiricalStdNs = reshape(single(predictedStd), outputSize);
    correction.stdToLifetimeContrast = reshape(single(stdToContrast), outputSize);
    correction.curveMonotonicAdjustmentNs = ...
        reshape(single(curveAdjustment), outputSize);
    correction.reliableMask = reshape(reliable, outputSize);
    correction.conservativelyClampedCountMask = ...
        reshape(conservativelyClamped, outputSize);
    correction.reasonCode = reshape(reasonCode, outputSize);
    correction.reasonDefinitions = reasonDefinitions();
    correction.config = cfg;
    correction.calibration = rmfield(calibration, ...
        {'forwardMean','forwardIsotonic','selectionRate','empiricalStd'});
    correction.summary = struct( ...
        'inputPixelCount', nnz(validInput), ...
        'candidatePixelCount', nnz(isfinite(candidate)), ...
        'reliablePixelCount', nnz(reliable), ...
        'reliableFractionOfInput', nnz(reliable) / max(nnz(validInput), 1), ...
        'conservativelyClampedPixelCount', nnz(conservativelyClamped), ...
        'medianAppliedCorrectionNs', finiteMedian(appliedCorrection(reliable)), ...
        'medianAbsoluteCorrectionNs', ...
            finiteMedian(abs(appliedCorrection(reliable))));
end

function cfg = fillDefaults(cfg)
    defaults = struct('minForwardSlope', 0.25, ...
        'minDisplaySelectionRate', 0.80, ...
        'maxEmpiricalStdNs', 0.25, ...
        'maxStdToLifetimeContrast', 0.50, ...
        'maxRelativeCorrection', 0.35, ...
        'maxCurveMonotonicAdjustmentNs', 0.05, ...
        'tauSlbNs', [], 'batchSize', 50000);
    cfg = mergeStruct(defaults, cfg);
    positiveScalar(cfg.minForwardSlope, 'cfg.minForwardSlope', false);
    boundedScalar(cfg.minDisplaySelectionRate, ...
        'cfg.minDisplaySelectionRate', 0, 1);
    positiveScalar(cfg.maxEmpiricalStdNs, 'cfg.maxEmpiricalStdNs', false);
    positiveScalar(cfg.maxStdToLifetimeContrast, ...
        'cfg.maxStdToLifetimeContrast', false);
    positiveScalar(cfg.maxRelativeCorrection, ...
        'cfg.maxRelativeCorrection', false);
    positiveScalar(cfg.maxCurveMonotonicAdjustmentNs, ...
        'cfg.maxCurveMonotonicAdjustmentNs', true);
    positiveScalar(cfg.batchSize, 'cfg.batchSize', false);
    if cfg.batchSize ~= round(cfg.batchSize)
        error('immune_cell_MIET_correct_long_lifetime_bias:BatchSize', ...
            'cfg.batchSize must be an integer.');
    end
    if ~isempty(cfg.tauSlbNs)
        positiveScalar(cfg.tauSlbNs, 'cfg.tauSlbNs', false);
    end
end

function [tau, slb, long, outputSize] = validateMaps(tau, slb, long)
    if ~isnumeric(tau) || ~isreal(tau) || ~isnumeric(slb) || ...
            ~isreal(slb) || ~isnumeric(long) || ~isreal(long)
        error('immune_cell_MIET_correct_long_lifetime_bias:InputType', ...
            'Lifetime and photon-count inputs must be real numeric arrays.');
    end
    if ~isequal(size(tau), size(slb), size(long))
        error('immune_cell_MIET_correct_long_lifetime_bias:InputSize', ...
            'Lifetime, SLB-count and long-count arrays must have the same size.');
    end
    outputSize = size(tau);
    tau = double(tau(:));
    slb = double(slb(:));
    long = double(long(:));
end

function calibration = loadCalibration(source, cfg)
    sourceFile = '';
    if ischar(source) || (isstring(source) && isscalar(source))
        sourceFile = char(source);
        if ~isfile(sourceFile)
            error('immune_cell_MIET_correct_long_lifetime_bias:CalibrationFile', ...
                'Calibration MAT does not exist: %s', sourceFile);
        end
        loaded = load(sourceFile, 'analysis');
        if ~isfield(loaded, 'analysis')
            error('immune_cell_MIET_correct_long_lifetime_bias:CalibrationMat', ...
                'Calibration MAT must contain an analysis struct.');
        end
        source = loaded.analysis;
    end
    if istable(source)
        summary = source;
        instrument = struct();
        estimator = struct();
    elseif isstruct(source) && isscalar(source) && isfield(source, 'summary')
        summary = source.summary;
        instrument = fieldOr(source, 'instrument', struct());
        estimator = fieldOr(source, 'estimator', struct());
    else
        error('immune_cell_MIET_correct_long_lifetime_bias:CalibrationType', ...
            'Calibration must be a MAT filename, analysis struct or summary table.');
    end
    required = {'trueLongLifetimeNs','slbPhotons','longPhotons', ...
        'meanPosteriorExpectedLongPhotons', ...
        'slbPriorScale','posteriorMeanEstimateNs','displaySelectionRate', ...
        'posteriorEmpiricalStdNs'};
    missing = required(~ismember(required, summary.Properties.VariableNames));
    if ~isempty(missing)
        error('immune_cell_MIET_correct_long_lifetime_bias:CalibrationSchema', ...
            'Calibration summary is missing %s.', missing{1});
    end
    scale = double(summary.slbPriorScale);
    use = isfinite(scale) & abs(scale - 1) <= 1e-8;
    summary = summary(use, :);
    if isempty(summary)
        error('immune_cell_MIET_correct_long_lifetime_bias:CalibrationScale', ...
            'Calibration has no rows with slbPriorScale == 1.');
    end

    tauAxis = unique(double(summary.trueLongLifetimeNs), 'sorted');
    slbAxis = unique(double(summary.slbPhotons), 'sorted');
    trueLongAxis = unique(double(summary.longPhotons), 'sorted');
    if numel(tauAxis) < 3 || numel(slbAxis) < 2 || numel(trueLongAxis) < 2
        error('immune_cell_MIET_correct_long_lifetime_bias:CalibrationGrid', ...
            'Calibration needs >=3 lifetimes and >=2 counts on each photon axis.');
    end
    trueGridSize = [numel(tauAxis), numel(slbAxis), numel(trueLongAxis)];
    forwardTrueGrid = nan(trueGridSize);
    selectionTrueGrid = nan(trueGridSize);
    empiricalStdTrueGrid = nan(trueGridSize);
    observedLongCountTrueGrid = nan(trueGridSize);
    for row = 1:height(summary)
        iTau = find(tauAxis == double(summary.trueLongLifetimeNs(row)), 1);
        iSlb = find(slbAxis == double(summary.slbPhotons(row)), 1);
        iLong = find(trueLongAxis == double(summary.longPhotons(row)), 1);
        if isfinite(forwardTrueGrid(iTau, iSlb, iLong))
            error('immune_cell_MIET_correct_long_lifetime_bias:DuplicateGrid', ...
                'Calibration contains duplicate lifetime/count conditions.');
        end
        forwardTrueGrid(iTau, iSlb, iLong) = ...
            double(summary.posteriorMeanEstimateNs(row));
        selectionTrueGrid(iTau, iSlb, iLong) = ...
            double(summary.displaySelectionRate(row));
        empiricalStdTrueGrid(iTau, iSlb, iLong) = ...
            double(summary.posteriorEmpiricalStdNs(row));
        observedLongCountTrueGrid(iTau, iSlb, iLong) = ...
            double(summary.meanPosteriorExpectedLongPhotons(row));
    end
    if any(~isfinite(forwardTrueGrid(:))) || ...
            any(~isfinite(selectionTrueGrid(:))) || ...
            any(~isfinite(empiricalStdTrueGrid(:))) || ...
            any(~isfinite(observedLongCountTrueGrid(:))) || ...
            any(observedLongCountTrueGrid(:) <= 0)
        error('immune_cell_MIET_correct_long_lifetime_bias:IncompleteGrid', ...
            'Calibration summary does not form a complete finite grid.');
    end

    % Real pixels provide the posterior-expected membrane photon count, not
    % the unknown true simulated count. Re-grid every lifetime/SLB slice onto
    % that observed count coordinate before constructing the inverse lookup.
    [longAxis, forward, selection, empiricalStd] = ...
        regridOnObservedLongCount(trueLongAxis, observedLongCountTrueGrid, ...
        forwardTrueGrid, selectionTrueGrid, empiricalStdTrueGrid);
    gridSize = size(forward);

    forwardIsotonic = zeros(gridSize);
    curveAdjustment = zeros(numel(slbAxis), numel(longAxis));
    for iSlb = 1:numel(slbAxis)
        for iLong = 1:numel(longAxis)
            raw = forward(:, iSlb, iLong);
            monotonic = isotonicIncreasing(raw);
            forwardIsotonic(:, iSlb, iLong) = monotonic;
            curveAdjustment(iSlb, iLong) = max(abs(monotonic - raw));
        end
    end

    tauSlb = NaN;
    if isfield(instrument, 'tauSlbNs')
        tauSlb = double(instrument.tauSlbNs);
    elseif ismember('fixedSlbLifetimeNs', summary.Properties.VariableNames)
        values = unique(double(summary.fixedSlbLifetimeNs));
        values = values(isfinite(values));
        if isscalar(values)
            tauSlb = values;
        end
    end
    if ~isempty(cfg.tauSlbNs)
        if isfinite(tauSlb) && abs(cfg.tauSlbNs - tauSlb) > ...
                max(0.01, 0.05 * tauSlb)
            error('immune_cell_MIET_correct_long_lifetime_bias:TauSlbMismatch', ...
                ['Requested tau_SLB %.4g ns differs from the calibration value ' ...
                 '%.4g ns. Generate a matched calibration.'], cfg.tauSlbNs, tauSlb);
        end
        tauSlb = cfg.tauSlbNs;
    end
    if ~isfinite(tauSlb)
        error('immune_cell_MIET_correct_long_lifetime_bias:TauSlbMissing', ...
            'tau_SLB is unavailable; provide cfg.tauSlbNs.');
    end

    calibration = struct('sourceFile', sourceFile, ...
        'tauSlbNs', tauSlb, 'trueLifetimeAxisNs', tauAxis(:).', ...
        'slbPhotonAxis', slbAxis(:).', 'longPhotonAxis', longAxis(:).', ...
        'longPhotonAxisMeaning', 'posterior-expected long-component photons', ...
        'sourceTrueLongPhotonAxis', trueLongAxis(:).', ...
        'forwardMean', forward, 'forwardIsotonic', forwardIsotonic, ...
        'selectionRate', selection, 'empiricalStd', empiricalStd, ...
        'curveMonotonicAdjustmentNs', curveAdjustment, ...
        'instrument', instrument, 'estimator', estimator);
end

function [observedAxis, forward, selection, empiricalStd] = ...
        regridOnObservedLongCount(trueAxis, observedCount, forwardTrue, ...
        selectionTrue, empiricalStdTrue)
    nTau = size(forwardTrue, 1);
    nSlb = size(forwardTrue, 2);
    sliceMin = nan(nTau, nSlb);
    sliceMax = nan(nTau, nSlb);
    for iTau = 1:nTau
        for iSlb = 1:nSlb
            values = squeeze(observedCount(iTau, iSlb, :));
            sliceMin(iTau, iSlb) = min(values);
            sliceMax(iTau, iSlb) = max(values);
        end
    end
    commonMinimum = max(sliceMin(:));
    commonMaximum = min(sliceMax(:));
    if ~(isfinite(commonMinimum) && isfinite(commonMaximum) && ...
            commonMaximum > commonMinimum)
        error('immune_cell_MIET_correct_long_lifetime_bias:ObservedCountRange', ...
            'No common fitted long-photon range exists across calibration slices.');
    end
    internal = trueAxis(trueAxis > commonMinimum & trueAxis < commonMaximum);
    observedAxis = unique([commonMinimum; internal(:); commonMaximum], 'sorted');
    if numel(observedAxis) < 2
        error('immune_cell_MIET_correct_long_lifetime_bias:ObservedCountGrid', ...
            'The fitted long-photon calibration range is too narrow.');
    end

    outputSize = [nTau, nSlb, numel(observedAxis)];
    forward = nan(outputSize);
    selection = nan(outputSize);
    empiricalStd = nan(outputSize);
    query = log(observedAxis);
    for iTau = 1:nTau
        for iSlb = 1:nSlb
            x = squeeze(observedCount(iTau, iSlb, :));
            [x, order] = sort(x);
            [x, uniqueIndex] = unique(x, 'stable');
            order = order(uniqueIndex);
            if numel(x) < 2
                error(['immune_cell_MIET_correct_long_lifetime_bias:' ...
                    'ObservedCountDegenerate'], ...
                    'A fitted long-photon calibration slice is degenerate.');
            end
            logX = log(x);
            forward(iTau, iSlb, :) = interp1(logX, ...
                squeeze(forwardTrue(iTau, iSlb, order)), query, 'linear');
            selection(iTau, iSlb, :) = interp1(logX, ...
                squeeze(selectionTrue(iTau, iSlb, order)), query, 'linear');
            empiricalStd(iTau, iSlb, :) = interp1(logX, ...
                squeeze(empiricalStdTrue(iTau, iSlb, order)), query, 'linear');
        end
    end
    if any(~isfinite(forward(:))) || any(~isfinite(selection(:))) || ...
            any(~isfinite(empiricalStd(:)))
        error('immune_cell_MIET_correct_long_lifetime_bias:ObservedCountRegrid', ...
            'Re-gridding onto fitted long-photon counts produced missing values.');
    end
end

function local = invertBatch(reported, slbCount, longCount, calibration, cfg)
    [slbLow, slbHigh, slbWeight] = countBracket( ...
        log(calibration.slbPhotonAxis), log(slbCount));
    [longLow, longHigh, longWeight] = countBracket( ...
        log(calibration.longPhotonAxis), log(longCount));
    nSlb = numel(calibration.slbPhotonAxis);
    nLong = numel(calibration.longPhotonAxis);
    index00 = sub2ind([nSlb nLong], slbLow, longLow);
    index10 = sub2ind([nSlb nLong], slbHigh, longLow);
    index01 = sub2ind([nSlb nLong], slbLow, longHigh);
    index11 = sub2ind([nSlb nLong], slbHigh, longHigh);
    weight00 = (1 - slbWeight) .* (1 - longWeight);
    weight10 = slbWeight .* (1 - longWeight);
    weight01 = (1 - slbWeight) .* longWeight;
    weight11 = slbWeight .* longWeight;

    forward = interpolateCurves(calibration.forwardIsotonic, ...
        index00, index10, index01, index11, ...
        weight00, weight10, weight01, weight11);
    selection = interpolateCurves(calibration.selectionRate, ...
        index00, index10, index01, index11, ...
        weight00, weight10, weight01, weight11);
    empiricalStd = interpolateCurves(calibration.empiricalStd, ...
        index00, index10, index01, index11, ...
        weight00, weight10, weight01, weight11);
    adjustmentGrid = calibration.curveMonotonicAdjustmentNs;
    curveAdjustment = adjustmentGrid(index00) .* weight00 + ...
        adjustmentGrid(index10) .* weight10 + ...
        adjustmentGrid(index01) .* weight01 + ...
        adjustmentGrid(index11) .* weight11;

    count = numel(reported);
    candidate = nan(count, 1);
    slope = nan(count, 1);
    selectedRate = nan(count, 1);
    stdNs = nan(count, 1);
    tauAxis = calibration.trueLifetimeAxisNs(:);
    assigned = false(count, 1);
    tolerance = 1e-10;
    for interval = 1:numel(tauAxis)-1
        low = forward(interval, :).';
        high = forward(interval + 1, :).';
        difference = high - low;
        use = ~assigned & difference > tolerance & ...
            reported >= low - tolerance & reported <= high + tolerance;
        if ~any(use)
            continue;
        end
        fraction = min(max((reported(use) - low(use)) ./ difference(use), 0), 1);
        candidate(use) = tauAxis(interval) + fraction * ...
            (tauAxis(interval + 1) - tauAxis(interval));
        slope(use) = difference(use) / ...
            (tauAxis(interval + 1) - tauAxis(interval));
        selectionLow = selection(interval, :).';
        selectionHigh = selection(interval + 1, :).';
        stdLow = empiricalStd(interval, :).';
        stdHigh = empiricalStd(interval + 1, :).';
        selectedRate(use) = selectionLow(use) + fraction .* ...
            (selectionHigh(use) - selectionLow(use));
        stdNs(use) = stdLow(use) + fraction .* ...
            (stdHigh(use) - stdLow(use));
        assigned(use) = true;
    end

    contrast = candidate - calibration.tauSlbNs;
    stdContrast = stdNs ./ max(contrast, eps);
    relativeCorrection = abs(candidate - reported) ./ max(candidate, eps);
    reason = ones(count, 1, 'uint8');
    reason(~assigned) = uint8(4);
    use = assigned & curveAdjustment > cfg.maxCurveMonotonicAdjustmentNs;
    reason(use) = uint8(5);
    use = assigned & reason == 1 & slope < cfg.minForwardSlope;
    reason(use) = uint8(6);
    use = assigned & reason == 1 & ...
        selectedRate < cfg.minDisplaySelectionRate;
    reason(use) = uint8(7);
    use = assigned & reason == 1 & stdNs > cfg.maxEmpiricalStdNs;
    reason(use) = uint8(8);
    use = assigned & reason == 1 & ...
        stdContrast > cfg.maxStdToLifetimeContrast;
    reason(use) = uint8(9);
    use = assigned & reason == 1 & ...
        relativeCorrection > cfg.maxRelativeCorrection;
    reason(use) = uint8(10);

    local = struct('candidate', candidate, 'forwardSlope', slope, ...
        'predictedSelection', selectedRate, 'predictedStd', stdNs, ...
        'stdToContrast', stdContrast, 'curveAdjustment', curveAdjustment, ...
        'reasonCode', reason);
end

function curves = interpolateCurves(grid, index00, index10, index01, ...
        index11, weight00, weight10, weight01, weight11)
    tauCount = size(grid, 1);
    flattened = reshape(grid, tauCount, []);
    curves = flattened(:, index00) .* weight00.' + ...
        flattened(:, index10) .* weight10.' + ...
        flattened(:, index01) .* weight01.' + ...
        flattened(:, index11) .* weight11.';
end

function [low, high, weight] = countBracket(logAxis, logValue)
    logAxis = double(logAxis(:));
    logValue = double(logValue(:));
    count = numel(logValue);
    low = ones(count, 1);
    high = ones(count, 1);
    weight = zeros(count, 1);
    for index = 1:numel(logAxis)-1
        use = logValue >= logAxis(index) & logValue <= logAxis(index + 1);
        low(use) = index;
        high(use) = index + 1;
        weight(use) = (logValue(use) - logAxis(index)) / ...
            (logAxis(index + 1) - logAxis(index));
    end
    atUpper = logValue >= logAxis(end);
    low(atUpper) = numel(logAxis);
    high(atUpper) = numel(logAxis);
    weight(atUpper) = 0;
end

function fitted = isotonicIncreasing(values)
%ISOTONICINCREASING Unweighted pool-adjacent-violators algorithm.
    values = double(values(:));
    blockMean = values;
    blockWeight = ones(size(values));
    blockStart = (1:numel(values)).';
    blockStop = blockStart;
    blockCount = numel(values);
    index = 1;
    while index < blockCount
        if blockMean(index) <= blockMean(index + 1)
            index = index + 1;
            continue;
        end
        combinedWeight = blockWeight(index) + blockWeight(index + 1);
        blockMean(index) = (blockWeight(index) * blockMean(index) + ...
            blockWeight(index + 1) * blockMean(index + 1)) / combinedWeight;
        blockWeight(index) = combinedWeight;
        blockStop(index) = blockStop(index + 1);
        blockMean(index + 1:blockCount - 1) = blockMean(index + 2:blockCount);
        blockWeight(index + 1:blockCount - 1) = blockWeight(index + 2:blockCount);
        blockStart(index + 1:blockCount - 1) = blockStart(index + 2:blockCount);
        blockStop(index + 1:blockCount - 1) = blockStop(index + 2:blockCount);
        blockCount = blockCount - 1;
        if index > 1
            index = index - 1;
        end
    end
    fitted = zeros(size(values));
    for index = 1:blockCount
        fitted(blockStart(index):blockStop(index)) = blockMean(index);
    end
end

function definitions = reasonDefinitions()
    definitions = struct( ...
        'code0', 'invalid or absent input', ...
        'code1', 'reliable inverse calibration; correction applied', ...
        'code2', 'long-component photons below calibration range', ...
        'code3', 'SLB photons above calibration range', ...
        'code4', 'reported lifetime outside invertible calibrated response', ...
        'code5', 'forward response is non-monotonic at these photon counts', ...
        'code6', 'forward response slope is too small for stable inversion', ...
        'code7', 'simulated display-selection probability is too low', ...
        'code8', 'simulated empirical lifetime spread is too large', ...
        'code9', 'uncertainty is too large relative to lifetime contrast from SLB', ...
        'code10', 'required correction is too large for safe lookup correction');
end

function value = fieldOr(container, name, fallback)
    value = fallback;
    if isfield(container, name)
        value = container.(name);
    end
end

function value = finiteMedian(data)
    data = double(data(isfinite(data)));
    if isempty(data)
        value = NaN;
    else
        value = median(data);
    end
end

function positiveScalar(value, name, allowZero)
    validateattributes(value, {'numeric'}, {'real','finite','scalar'}, ...
        mfilename, name);
    if (allowZero && value < 0) || (~allowZero && value <= 0)
        error('immune_cell_MIET_correct_long_lifetime_bias:ConfigValue', ...
            '%s has an invalid value.', name);
    end
end

function boundedScalar(value, name, lower, upper)
    validateattributes(value, {'numeric'}, {'real','finite','scalar'}, ...
        mfilename, name);
    if value < lower || value > upper
        error('immune_cell_MIET_correct_long_lifetime_bias:ConfigRange', ...
            '%s must lie in [%g, %g].', name, lower, upper);
    end
end

function out = mergeStruct(base, override)
    if ~(isstruct(override) && isscalar(override))
        error('immune_cell_MIET_correct_long_lifetime_bias:Config', ...
            'cfg must be a scalar struct.');
    end
    out = base;
    names = fieldnames(override);
    for index = 1:numel(names)
        out.(names{index}) = override.(names{index});
    end
end
