function immune_cell_MIET_biexp_report(out, outputDir)
%IMMUNE_CELL_MIET_BIEXP_REPORT Print and write a scalar summary of the fit.
%
% The soft-constraint diagnostics are the point of this summary. If the fitted
% tau1 sits at the edge of the prior across most pixels, the prior is fighting
% the data and its centre or width is wrong - that has to be visible rather than
% buried in a map.
%
% Pinning is measured as the fraction of pixels landing on the FIRST or LAST
% available tau1 node, NOT as |pull| > 1.8. The sigma threshold was unsound
% because it is TWO-SIDED while the truncation is one-sided: the positivity
% filter can only ever drop LOW nodes, so on a short-prior acquisition the low
% reach shrinks to -1 sigma while +2 sigma stays available. On 155036 that let
% 62.5%% of pixels sit on the lowest surviving node while the old statistic
% read 5.7e-05 - which printed as "0.0%%". (The earlier claim in this header,
% that the threshold could NEVER be met, was wrong: eight pixels did reach the
% surviving +2 sigma node. The flaw is the two-sidedness, not unreachability.)

    maps = out.maps;
    valid = isfinite(maps.tau1Ns);
    pull = maps.slbPullSigma(valid);
    tau2 = maps.tau2Ns(valid);
    f2 = maps.photonFraction2(valid);
    bg = maps.backgroundFraction(valid);
    dev = maps.reducedDeviance(valid);

    fprintf('\n  RESULT: %d pixel(s) fitted\n', nnz(valid));
    fprintf('      tau1 (SLB, soft)   median %.4f ns   prior centre %.4f\n', ...
        median(maps.tau1Ns(valid)), out.opts.slbTauNs);
    if isfield(maps, 'tau1AtGridEdge')
        atEdge = mean(double(maps.tau1AtGridEdge(valid)));
    else
        atEdge = NaN;   % maps written before this diagnostic existed
    end
    % Reach must be computed from the GRID, not from the pulls that happen to
    % occur: max(abs(pull)) reports the most extreme node any pixel occupied,
    % which on every one of these datasets is +2 because the high side is never
    % truncated - so a low-side truncation was invisible and the NOTE below
    % fired nowhere. Take the signed low edge instead.
    if isfield(out, 'tau1Grid') && ~isempty(out.tau1Grid)
        reach = (min(out.tau1Grid) - out.opts.slbTauNs) / ...
            max(out.opts.slbSigmaNs, eps);
    else
        reach = -max(abs(pull));   % pre-tau1Grid maps: best available proxy
    end
    fprintf(['      prior pull         median %+.2f sigma (grid low edge ' ...
        '%+.2f sigma)\n'], median(pull), reach);
    fprintf('      tau1 at grid edge  %.1f%% of pixels\n', 100 * atEdge);
    if atEdge > 0.5
        fprintf(['      WARNING: most pixels are jammed against the END of ' ...
            'the tau1 grid, so\n      tau1 is NOT determined here - it is ' ...
            'only bounded. Pin slbTauNs to a\n      value supported across ' ...
            'the session, or widen slbSigmaNs.\n']);
    end
    if reach > -1.9
        fprintf(['      NOTE: the tau1 grid was truncated by the positivity ' ...
            'floor, so it reaches\n      only %+.2f sigma below centre. A prior centre of ' ...
            '%.4f ns is close to zero relative to its\n      width, which ' ...
            'is itself a warning about the reference.\n'], reach, ...
            out.opts.slbTauNs);
    end
    fprintf('      tau2 (free)        median %.3f ns, IQR [%.3f %.3f]\n', ...
        median(tau2), quantileLocalBiexp(tau2, 0.25), ...
        quantileLocalBiexp(tau2, 0.75));
    fprintf('      photon share tau2  median %.3f, IQR [%.3f %.3f]\n', ...
        median(f2), quantileLocalBiexp(f2, 0.25), ...
        quantileLocalBiexp(f2, 0.75));
    if isfield(maps, 'speciesFraction2')
        s2 = maps.speciesFraction2(valid);
        fprintf(['      species share tau2 median %.3f (pre-exponential, ' ...
            'a/S)\n'], ...
            median(s2));
    end
    if isfield(maps, 'tauMeanNs')
        tm = maps.tauMeanNs(valid);
        fprintf(['      photon-weighted tau median %.3f ns  <- the map a ' ...
            'MIET height would use\n'], median(tm));
    end
    fprintf('      background share   median %.4f of the pixel photons\n', ...
        median(bg));
    fprintf('      reduced deviance   median %.3f, 90th pct %.3f\n', ...
        median(dev), quantileLocalBiexp(dev, 0.90));

    rows = struct('pixelsFitted', nnz(valid), ...
        'slbPriorCentreNs', out.opts.slbTauNs, ...
        'slbPriorSigmaNs', out.opts.slbSigmaNs, ...
        'tau1MedianNs', median(maps.tau1Ns(valid)), ...
        'priorPullMedianSigma', median(pull), ...
        'tau1AtGridEdgeFraction', atEdge, ...
        'priorPullReachableSigma', reach, ...
        'tau2MedianNs', median(tau2), ...
        'tau2Q1Ns', quantileLocalBiexp(tau2, 0.25), ...
        'tau2Q3Ns', quantileLocalBiexp(tau2, 0.75), ...
        'photonShare2Median', median(f2), ...
        'backgroundShareMedian', median(bg), ...
        'reducedDevianceMedian', median(dev), ...
        'reducedDevianceP90', quantileLocalBiexp(dev, 0.90), ...
        'binSize', out.opts.binSize, ...
        'elapsedSeconds', out.elapsedSeconds);
    csvFile = fullfile(outputDir, 'biexp_slb_summary.csv');
    writetable(struct2table(rows), csvFile);
    fprintf('  wrote %s\n', csvFile);
end
