function result = PTU_MitoLysoCytosol_BayesFLIM(ptuFile, cfg)
%PTU_MITOLYSOCYTOSOL_BAYESFLIM Segment organelles and fit B12 FLIM.
%
% This is the public orchestration function. All numerical operations are in
% separate files under b12. The only public input structure is cfg and
% the only analysis output structure is result.
%
% Default channel assignment:
%   mitochondrial segmentation: laser 3 (640 nm), detector 2 = L3D2
%   B12 lifetime analysis:       laser 2 (560 nm), detector 1 = L2D1
%
% Example:
%   cfg = struct('showFigures', true, 'saveOutputs', true);
%   result = PTU_MitoLysoCytosol_BayesFLIM('D:\data\RawImage.ptu', cfg);

    %% Validate the public input
    if nargin < 2 || isempty(cfg)
        cfg = struct();
    end
    % The helper folder is ordinary MATLAB code, not a +package namespace.
    helperFolder = fullfile(fileparts(mfilename('fullpath')), 'b12');
    if ~isfolder(helperFolder)
        error('Required helper folder was not found: %s', helperFolder);
    end
    pathEntries = strsplit(path, pathsep);
    helperWasOnPath = any(strcmpi(pathEntries, helperFolder));
    if ~helperWasOnPath
        addpath(helperFolder, '-begin');
        helperPathCleanup = onCleanup(@() rmpath(helperFolder));
    end
    cfg = defaultConfig(cfg);
    if ~(ischar(ptuFile) || isstring(ptuFile)) || ~isfile(ptuFile)
        error('ptuFile must identify an existing PTU file.');
    end
    ptuFile = char(ptuFile);
    if cfg.cnum < max(cfg.mitoPulseIndex, cfg.b12PulseIndex)
        error('A requested laser index exceeds cfg.cnum.');
    end
    requiredFunctions = {'PTU_FLIM_GPU', 'flim_bayes_lowphoton', ...
        'Calc_mIRF_Global_GammaShifted_fast'};
    for k = 1:numel(requiredFunctions)
        if exist(requiredFunctions{k}, 'file') ~= 2
            error('Required function %s.m is not on the MATLAB path.', requiredFunctions{k});
        end
    end
    if exist('bwconncomp', 'file') ~= 2 || exist('bwconvhull', 'file') ~= 2
        error('This analysis requires MATLAB Image Processing Toolbox.');
    end

    %% Read photon lists at a practical coarse TCSPC resolution
    fprintf('Reading PTU photon lists: %s\n', ptuFile);
    % PTU_FLIM_GPU has a legacy structure input; no package helper receives it.
    readOptions = struct('photonsPerChunk', cfg.photonsPerChunk, ...
        'computePerFrame', false, 'storeTcspcPix', false, ...
        'storePhotonLists', true, 'storeTimeCell', false, ...
        'showWaitbar', cfg.showWaitbar, ...
        'minLifetimeBin_ns', cfg.tcspcBinNs, 'maxNgate', cfg.maxNgate);
    ptu = PTU_FLIM_GPU(ptuFile, readOptions);
    if isempty(ptu.im_tcspc) || isempty(ptu.im_chan)
        error('PTU_FLIM_GPU did not return photon timing/channel lists.');
    end
    nx = double(ptu.head.ImgHdr_PixX);
    ny = double(ptu.head.ImgHdr_PixY);
    totalGateBins = double(ptu.Ngate);
    if isfield(ptu, 'Resolution_ns') && ~isempty(ptu.Resolution_ns)
        dtNs = double(ptu.Resolution_ns);
    else
        dtNs = double(ptu.head.MeasDesc_Resolution) * 1e9;
    end

    %% Detect the three rise-referenced laser gates
    detectorIds = activeDetectorIds(ptu.im_chan, ptu.dind);
    requiredDetector = max(cfg.mitoDetectorIndex, cfg.b12DetectorIndex);
    if numel(detectorIds) < requiredDetector
        error('Requested detector %d, but raw detector IDs [%s] were recorded.', ...
            requiredDetector, num2str(detectorIds(:).'));
    end
    detectorTcspc = detectorHistogram( ...
        ptu.im_tcspc, ptu.im_chan, detectorIds, totalGateBins);
    preGateBins = max(1, round(cfg.gatePreNs / dtNs));
    [gateStarts, gateStops, gateLength, gateProfile, smoothGateProfile, ...
        gateThreshold, gateBaseline, riseBins, peakBins, peakHeights, ...
        rawGateStarts, rawGateStops, rawGateScores] = detectGates( ...
        detectorTcspc, cfg.cnum, cfg.gateThresholdFrac, preGateBins, ...
        cfg.minGateSeparationBins, cfg.secondPeakMinFraction);
    fprintf('Detected gates [%s], common length %d bins (%.2f ns).\n', ...
        num2str(gateStarts(:).'), gateLength, gateLength * dtNs);

    %% Extract L3D2 mitochondria photons and L2D1 B12 photons
    mitoDetectorId = detectorIds(cfg.mitoDetectorIndex);
    b12DetectorId = detectorIds(cfg.b12DetectorIndex);
    [~, mitoPixels] = selectGate(ptu.im_tcspc, ptu.im_chan, ...
        ptu.im_col, ptu.im_line, mitoDetectorId, ...
        gateStarts(cfg.mitoPulseIndex), gateLength, totalGateBins, nx, ny);
    [b12Bins, b12Pixels] = selectGate(ptu.im_tcspc, ptu.im_chan, ...
        ptu.im_col, ptu.im_line, b12DetectorId, ...
        gateStarts(cfg.b12PulseIndex), gateLength, totalGateBins, nx, ny);
    mitoIntensity = photonImage(mitoPixels, nx, ny);
    b12Intensity = photonImage(b12Pixels, nx, ny);
    if ~any(b12Intensity(:) > 0)
        error('No photons were found in B12 channel L%dD%d.', ...
            cfg.b12PulseIndex, cfg.b12DetectorIndex);
    end

    %% Segment a filled cell boundary and its three compartments
    fprintf('Segmenting filled cell boundary, mitochondria, and lysosomes...\n');
    [cellMask, cellBoundary, mitoMask, lysoMask, cytosolMask, ...
        compartmentMap, mitoLabels, lysoLabels, cellDetectionImage, ...
        cellThreshold, mitoEnhanced, mitoThreshold, lysosomeResponse, ...
        lysosomeThreshold, lysosomeBrightThreshold] = segmentCompartments( ...
        mitoIntensity, b12Intensity, cfg.cellSmoothSigma, ...
        cfg.cellThresholdScale, cfg.cellCloseRadius, ...
        cfg.cellDilateRadius, cfg.minCellArea, cfg.mitoSmoothSigma, ...
        cfg.mitoBackgroundRadius, cfg.mitoThresholdScale, ...
        cfg.mitoCloseRadius, cfg.mitoDilateRadius, cfg.minMitoArea, ...
        cfg.lysoSigmaSmall, cfg.lysoSigmaLarge, cfg.lysoThresholdMAD, ...
        cfg.lysoMinPeakFraction, cfg.lysoBrightQuantile, ...
        cfg.lysoExcludeMitoRadius, cfg.lysoCloseRadius, ...
        cfg.lysoDilateRadius, cfg.minLysoArea);
    mitoRegionCount = max(mitoLabels(:));
    lysoRegionCount = max(lysoLabels(:));
    fprintf('Found %d mitochondrial and %d lysosome connected regions.\n', ...
        mitoRegionCount, lysoRegionCount);

    %% Extract B12 TCSPC curves from every connected region
    globalCurve = curveForMask(b12Bins, b12Pixels, true(nx, ny), gateLength);
    [mitoCurves, mitoPhotonCounts] = curvesForLabels( ...
        b12Bins, b12Pixels, mitoLabels, gateLength);
    [lysoCurves, lysoPhotonCounts] = curvesForLabels( ...
        b12Bins, b12Pixels, lysoLabels, gateLength);
    cytosolCurve = curveForMask(b12Bins, b12Pixels, cytosolMask, gateLength);
    timeNs = ((0:gateLength-1)' + 0.5) * dtNs;
    pulsePeriodNs = double(ptu.head.MeasDesc_GlobalResolution) * 1e9;

    %% Estimate or load the B12 IRF
    [irf, irfSource, irfParameters, irfTau, irfFit, irfChi] = ...
        estimateIrf(globalCurve, dtNs, cfg.irf, ...
        cfg.minPhotonsForIRF, cfg.useGPU, cfg.irfNCasc, cfg.irfNSub, cfg.irfTau0);

    %% Select one or two exponentials for pooled and connected-region curves
    fitArguments = {irf, dtNs, cfg.maxExp, cfg.tauSeeds1, cfg.tauSeeds2, ...
        cfg.tauBoundsNs, cfg.includeBackground, cfg.minPhotonsPerRegionFit, ...
        cfg.fitMaxIter, cfg.bicImprovementForTwoExp, ...
        cfg.minStateSeparationFraction, cfg.minStateAmplitudeFraction};
    [globalOk, globalOrder, globalTau, globalTauMean, globalCoeff, globalFraction, ...
        globalFitCounts, globalMetrics, globalMessage] = ...
        selectModel(globalCurve, fitArguments{:});
    [cytosolOk, cytosolOrder, cytosolTau, cytosolTauMean, cytosolCoeff, ...
        cytosolFraction, cytosolFitCounts, cytosolMetrics, cytosolMessage] = ...
        selectModel(cytosolCurve, fitArguments{:});
    [pooledMitoOk, pooledMitoOrder, pooledMitoTau, pooledMitoTauMean, ...
        pooledMitoCoeff, pooledMitoFraction, pooledMitoFitCounts, ...
        pooledMitoMetrics, pooledMitoMessage] = ...
        selectModel(sum(mitoCurves, 2), fitArguments{:});
    [pooledLysoOk, pooledLysoOrder, pooledLysoTau, pooledLysoTauMean, ...
        pooledLysoCoeff, pooledLysoFraction, pooledLysoFitCounts, ...
        pooledLysoMetrics, pooledLysoMessage] = ...
        selectModel(sum(lysoCurves, 2), fitArguments{:});
    [mitoOk, mitoOrder, mitoTau, mitoTauMean, mitoCoeff, mitoFraction, ...
        mitoFitCounts, mitoMetrics, mitoMessages] = fitRegions( ...
        mitoCurves, 'mitochondrion', fitArguments{:});
    [lysoOk, lysoOrder, lysoTau, lysoTauMean, lysoCoeff, lysoFraction, ...
        lysoFitCounts, lysoMetrics, lysoMessages] = fitRegions( ...
        lysoCurves, 'lysosome', fitArguments{:});

    %% Run Bayesian maps, retaining regional values in photon-poor interior pixels
    fprintf('Building B12 TCSPC cube and Bayesian compartment maps...\n');
    b12Cube = photonCube(b12Bins, b12Pixels, nx, ny, gateLength);
    floatMaps = nan(nx, ny, 11, 'single');
    modelOrderMap = zeros(nx, ny, 'uint8');
    posteriorEvaluated = false(nx, ny);

    mitoBayesOk = false(mitoRegionCount, 1);
    mitoBayesMessages = cell(mitoRegionCount, 1);
    mitoBayesPhotons = zeros(mitoRegionCount, 1);
    mitoBayesTau = nan(mitoRegionCount, 2);
    mitoBayesModelSummary = zeros(mitoRegionCount, 3);
    for region = 1:mitoRegionCount
        if mitoOk(region)
            seedTau = mitoTau(region, :);
            seedTauMean = mitoTauMean(region);
            seedFraction = mitoFraction(region, :);
        elseif pooledMitoOk
            seedTau = pooledMitoTau;
            seedTauMean = pooledMitoTauMean;
            seedFraction = pooledMitoFraction;
        else
            seedTau = globalTau;
            seedTauMean = globalTauMean;
            seedFraction = globalFraction;
        end
        regionMask = mitoLabels == region;
        [floatPatch, modelPatch, posteriorPatch, xRange, yRange, ...
            mitoBayesOk(region), mitoBayesMessages{region}, mitoBayesPhotons(region), ...
            mitoBayesTau(region, :), mitoBayesModelSummary(region, :)] = ...
            bayesPatch(b12Cube, regionMask, seedTau, seedTauMean, ...
            seedFraction, irf, pulsePeriodNs, dtNs, cfg.useGPU, ...
            cfg.bayesBatchSize, cfg.includeBackground, cfg.bayesMinPixelPhotons, ...
            cfg.bayesMinRegionPhotons, cfg.bayesSignalGrid, ...
            cfg.bayesFractionGrid, cfg.bayesSingleTauGrid, cfg.bayesShiftBounds, ...
            cfg.minStateSeparationFraction, cfg.minStateAmplitudeFraction);
        [floatMaps, modelOrderMap, posteriorEvaluated] = insertPatch( ...
            floatMaps, modelOrderMap, posteriorEvaluated, floatPatch, modelPatch, ...
            posteriorPatch, xRange, yRange, regionMask);
    end

    lysoBayesOk = false(lysoRegionCount, 1);
    lysoBayesMessages = cell(lysoRegionCount, 1);
    lysoBayesPhotons = zeros(lysoRegionCount, 1);
    lysoBayesTau = nan(lysoRegionCount, 2);
    lysoBayesModelSummary = zeros(lysoRegionCount, 3);
    for region = 1:lysoRegionCount
        if lysoOk(region)
            seedTau = lysoTau(region, :);
            seedTauMean = lysoTauMean(region);
            seedFraction = lysoFraction(region, :);
        elseif pooledLysoOk
            seedTau = pooledLysoTau;
            seedTauMean = pooledLysoTauMean;
            seedFraction = pooledLysoFraction;
        else
            seedTau = globalTau;
            seedTauMean = globalTauMean;
            seedFraction = globalFraction;
        end
        regionMask = lysoLabels == region;
        [floatPatch, modelPatch, posteriorPatch, xRange, yRange, ...
            lysoBayesOk(region), lysoBayesMessages{region}, lysoBayesPhotons(region), ...
            lysoBayesTau(region, :), lysoBayesModelSummary(region, :)] = ...
            bayesPatch(b12Cube, regionMask, seedTau, seedTauMean, ...
            seedFraction, irf, pulsePeriodNs, dtNs, cfg.useGPU, ...
            cfg.bayesBatchSize, cfg.includeBackground, cfg.bayesMinPixelPhotons, ...
            cfg.bayesMinRegionPhotons, cfg.bayesSignalGrid, ...
            cfg.bayesFractionGrid, cfg.bayesSingleTauGrid, cfg.bayesShiftBounds, ...
            cfg.minStateSeparationFraction, cfg.minStateAmplitudeFraction);
        [floatMaps, modelOrderMap, posteriorEvaluated] = insertPatch( ...
            floatMaps, modelOrderMap, posteriorEvaluated, floatPatch, modelPatch, ...
            posteriorPatch, xRange, yRange, regionMask);
    end

    if cytosolOk
        cytosolSeedTau = cytosolTau;
        cytosolSeedMean = cytosolTauMean;
        cytosolSeedFraction = cytosolFraction;
    else
        cytosolSeedTau = globalTau;
        cytosolSeedMean = globalTauMean;
        cytosolSeedFraction = globalFraction;
    end
    [floatPatch, modelPatch, posteriorPatch, xRange, yRange, ...
        cytosolBayesOk, cytosolBayesMessage, cytosolBayesPhotons, ...
        cytosolBayesTau, cytosolBayesModelSummary] = bayesPatch( ...
        b12Cube, cytosolMask, cytosolSeedTau, cytosolSeedMean, ...
        cytosolSeedFraction, irf, pulsePeriodNs, dtNs, cfg.useGPU, ...
        cfg.bayesBatchSize, cfg.includeBackground, cfg.bayesMinPixelPhotons, ...
        cfg.bayesMinRegionPhotons, cfg.bayesSignalGrid, cfg.bayesFractionGrid, ...
        cfg.bayesSingleTauGrid, cfg.bayesShiftBounds, ...
        cfg.minStateSeparationFraction, cfg.minStateAmplitudeFraction);
    [floatMaps, modelOrderMap, posteriorEvaluated] = insertPatch( ...
        floatMaps, modelOrderMap, posteriorEvaluated, floatPatch, modelPatch, ...
        posteriorPatch, xRange, yRange, cytosolMask);
    clear b12Cube

    %% Package all arrays into the single public result structure
    result = struct();
    result.file = ptuFile;
    result.config = cfg;
    result.head = ptu.head;
    result.detectorIdsRaw = detectorIds;
    result.channelMapping = struct( ...
        'mitochondria', sprintf('L%dD%d (raw detector %d)', ...
        cfg.mitoPulseIndex, cfg.mitoDetectorIndex, mitoDetectorId), ...
        'b12', sprintf('L%dD%d (raw detector %d)', ...
        cfg.b12PulseIndex, cfg.b12DetectorIndex, b12DetectorId));
    result.gates = struct('startsBin', gateStarts, 'stopsBin', gateStops, ...
        'lengthBins', gateLength, 'dtNs', dtNs, 'profile', gateProfile, ...
        'smoothProfile', smoothGateProfile, 'threshold', gateThreshold, ...
        'baseline', gateBaseline, 'riseBins', riseBins, 'peakBins', peakBins, ...
        'peakHeights', peakHeights, 'rawStarts', rawGateStarts, ...
        'rawStops', rawGateStops, 'rawScores', rawGateScores, ...
        'preBins', preGateBins, 'preNs', cfg.gatePreNs);
    result.intensity = struct('mitochondria640Det2', mitoIntensity, ...
        'b12_560Det1', b12Intensity);
    result.masks = struct('cell', cellMask, 'cellBoundary', cellBoundary, ...
        'mitochondria', mitoMask, 'lysosome', lysoMask, ...
        'cytosol', cytosolMask, 'compartmentMap', compartmentMap);
    result.labels = struct('mitochondria', mitoLabels, 'lysosome', lysoLabels);
    result.regions = struct( ...
        'mitochondria', regionprops(mitoLabels, b12Intensity, ...
        'Area', 'Centroid', 'BoundingBox', 'MeanIntensity', 'MaxIntensity'), ...
        'lysosome', regionprops(lysoLabels, b12Intensity, ...
        'Area', 'Centroid', 'BoundingBox', 'MeanIntensity', 'MaxIntensity'));
    result.segmentation = struct('cellDetectionImageB12', cellDetectionImage, ...
        'cellThreshold', cellThreshold, 'mitochondriaEnhanced', mitoEnhanced, ...
        'mitochondriaThreshold', mitoThreshold, ...
        'lysosomeCoarseResponse', lysosomeResponse, ...
        'lysosomeContrastThreshold', lysosomeThreshold, ...
        'lysosomeBrightThreshold', lysosomeBrightThreshold, ...
        'cellBoundaryMethod', 'per-object convex hull followed by hole filling');
    result.tcspc = struct('timeNs', timeNs, 'globalB12', globalCurve, ...
        'mitochondria', mitoCurves, 'lysosome', lysoCurves, ...
        'cytosol', cytosolCurve, 'mitochondriaPhotonCounts', mitoPhotonCounts, ...
        'lysosomePhotonCounts', lysoPhotonCounts);
    result.irf = struct('curve', irf, 'source', irfSource, ...
        'parameters', irfParameters, 'tauFitNs', irfTau, ...
        'fitCounts', irfFit, 'chi2red', irfChi);

    result.fits.globalB12 = struct('ok', globalOk, 'modelOrder', globalOrder, ...
        'tauNs', globalTau, 'tauMeanNs', globalTauMean, ...
        'coefficientsBgComp1Comp2', globalCoeff, 'speciesFraction', globalFraction, ...
        'fitCounts', globalFitCounts, 'metrics', globalMetrics, 'message', globalMessage);
    result.fits.cytosol = struct('ok', cytosolOk, 'modelOrder', cytosolOrder, ...
        'tauNs', cytosolTau, 'tauMeanNs', cytosolTauMean, ...
        'coefficientsBgComp1Comp2', cytosolCoeff, 'speciesFraction', cytosolFraction, ...
        'fitCounts', cytosolFitCounts, 'metrics', cytosolMetrics, 'message', cytosolMessage);
    result.fits.pooledMitochondria = struct('ok', pooledMitoOk, ...
        'modelOrder', pooledMitoOrder, 'tauNs', pooledMitoTau, ...
        'tauMeanNs', pooledMitoTauMean, 'coefficientsBgComp1Comp2', pooledMitoCoeff, ...
        'speciesFraction', pooledMitoFraction, 'fitCounts', pooledMitoFitCounts, ...
        'metrics', pooledMitoMetrics, 'message', pooledMitoMessage);
    result.fits.pooledLysosome = struct('ok', pooledLysoOk, ...
        'modelOrder', pooledLysoOrder, 'tauNs', pooledLysoTau, ...
        'tauMeanNs', pooledLysoTauMean, 'coefficientsBgComp1Comp2', pooledLysoCoeff, ...
        'speciesFraction', pooledLysoFraction, 'fitCounts', pooledLysoFitCounts, ...
        'metrics', pooledLysoMetrics, 'message', pooledLysoMessage);
    result.fits.mitochondria = struct('ok', mitoOk, 'modelOrder', mitoOrder, ...
        'tauNs', mitoTau, 'tauMeanNs', mitoTauMean, ...
        'coefficientsBgComp1Comp2', mitoCoeff, 'speciesFraction', mitoFraction, ...
        'fitCounts', mitoFitCounts, 'metrics', mitoMetrics, 'messages', {mitoMessages});
    result.fits.lysosome = struct('ok', lysoOk, 'modelOrder', lysoOrder, ...
        'tauNs', lysoTau, 'tauMeanNs', lysoTauMean, ...
        'coefficientsBgComp1Comp2', lysoCoeff, 'speciesFraction', lysoFraction, ...
        'fitCounts', lysoFitCounts, 'metrics', lysoMetrics, 'messages', {lysoMessages});
    result.fits.metricColumns = {'deviance', 'BIC', 'reducedChiSquare', ...
        'photonCount', 'oneExpBIC', 'twoExpBIC', 'oneExpChi2', 'twoExpChi2'};

    result.flim = struct('tauMeanNs', floatMaps(:, :, 1), ...
        'tauStdNs', floatMaps(:, :, 2), 'tauMapNs', floatMaps(:, :, 3), ...
        'signalFraction', floatMaps(:, :, 4), ...
        'componentLifetimeNs', floatMaps(:, :, 5:6), ...
        'componentAmplitude', floatMaps(:, :, 7:8), ...
        'componentFraction', floatMaps(:, :, 9:10), ...
        'backgroundAmplitude', floatMaps(:, :, 11), ...
        'modelOrder', modelOrderMap, 'posteriorEvaluated', posteriorEvaluated, ...
        'compartment', compartmentMap);
    result.bayes.mitochondria = struct('ok', mitoBayesOk, ...
        'messages', {mitoBayesMessages}, 'photonCounts', mitoBayesPhotons, ...
        'posteriorTauNs', mitoBayesTau, 'modelSummary', mitoBayesModelSummary);
    result.bayes.lysosome = struct('ok', lysoBayesOk, ...
        'messages', {lysoBayesMessages}, 'photonCounts', lysoBayesPhotons, ...
        'posteriorTauNs', lysoBayesTau, 'modelSummary', lysoBayesModelSummary);
    result.bayes.cytosol = struct('ok', cytosolBayesOk, ...
        'message', cytosolBayesMessage, 'photonCount', cytosolBayesPhotons, ...
        'posteriorTauNs', cytosolBayesTau, 'modelSummary', cytosolBayesModelSummary);

    %% Create a limited set of diagnostic and result figures
    figureHandles = gobjects(0);
    if cfg.showFigures || cfg.saveOutputs
        if cfg.showFigures
            visibility = 'on';
        else
            visibility = 'off';
        end
        figureHandles = gobjects(5, 1);
        figureHandles(1) = showSegmentation(mitoIntensity, b12Intensity, ...
            mitoMask, lysoMask, cellBoundary, compartmentMap, ...
            mitoRegionCount, lysoRegionCount, visibility);
        figureHandles(2) = showFlim(b12Intensity, floatMaps(:, :, 1), ...
            floatMaps(:, :, 2), modelOrderMap, posteriorEvaluated, ...
            compartmentMap, visibility);
        figureHandles(3) = showComponents(floatMaps(:, :, 5:6), ...
            floatMaps(:, :, 7:8), floatMaps(:, :, 9:10), ...
            floatMaps(:, :, 11), visibility);

        fitNames = {'Global B12', 'Cytosol'};
        fitCurves = {globalCurve, cytosolCurve};
        fittedCurves = {globalFitCounts, cytosolFitCounts};
        fitOrders = [globalOrder; cytosolOrder];
        fitTau = [globalTau; cytosolTau];
        fitMessages = {globalMessage; cytosolMessage};
        [~, mitoPlotOrder] = sort(mitoPhotonCounts, 'descend');
        for k = 1:min(4, numel(mitoPlotOrder))
            region = mitoPlotOrder(k);
            fitNames{end + 1} = sprintf('Mito %d', region); %#ok<AGROW>
            fitCurves{end + 1} = mitoCurves(:, region); %#ok<AGROW>
            fittedCurves{end + 1} = mitoFitCounts(:, region); %#ok<AGROW>
            fitOrders(end + 1, 1) = mitoOrder(region); %#ok<AGROW>
            fitTau(end + 1, :) = mitoTau(region, :); %#ok<AGROW>
            fitMessages{end + 1, 1} = mitoMessages{region}; %#ok<AGROW>
        end
        [~, lysoPlotOrder] = sort(lysoPhotonCounts, 'descend');
        for k = 1:min(4, numel(lysoPlotOrder))
            region = lysoPlotOrder(k);
            fitNames{end + 1} = sprintf('Lyso %d', region); %#ok<AGROW>
            fitCurves{end + 1} = lysoCurves(:, region); %#ok<AGROW>
            fittedCurves{end + 1} = lysoFitCounts(:, region); %#ok<AGROW>
            fitOrders(end + 1, 1) = lysoOrder(region); %#ok<AGROW>
            fitTau(end + 1, :) = lysoTau(region, :); %#ok<AGROW>
            fitMessages{end + 1, 1} = lysoMessages{region}; %#ok<AGROW>
        end
        figureHandles(4) = showFits(timeNs, fitNames, fitCurves, ...
            fittedCurves, fitOrders, fitTau, fitMessages, cfg.maxFitPlots, visibility);
        figureHandles(5) = showLifetimeHistograms(mitoTau, mitoOrder, ...
            lysoTau, lysoOrder, cfg.tauBoundsNs, ...
            cfg.lifetimeHistogramBins, visibility);
    end

    %% Save only the compact result and rendered figures, not the TCSPC cube
    if cfg.saveOutputs
        if isempty(cfg.outputDir)
            outputDirectory = fullfile(fileparts(ptuFile), 'B12_BayesFLIM');
        else
            outputDirectory = cfg.outputDir;
        end
        if ~isfolder(outputDirectory)
            mkdir(outputDirectory);
        end
        matPath = fullfile(outputDirectory, [cfg.outputStem '.mat']);
        suffixes = {'segmentation', 'flim', 'components', 'fits', ...
            'lifetime_histograms'};
        figurePaths = cell(numel(figureHandles), 1);
        for k = 1:numel(figureHandles)
            figurePaths{k} = fullfile(outputDirectory, ...
                sprintf('%s_%s.png', cfg.outputStem, suffixes{k}));
            if exist('exportgraphics', 'file') == 2
                exportgraphics(figureHandles(k), figurePaths{k}, 'Resolution', 200);
            else
                saveas(figureHandles(k), figurePaths{k});
            end
        end
        result.savedOutputs = struct('directory', outputDirectory, ...
            'mat', matPath, 'figures', {figurePaths});
        save(matPath, 'result', '-v7.3');
    else
        result.savedOutputs = struct();
    end
    fprintf('B12 compartment Bayes FLIM analysis complete.\n');
end
