%RUN_IMMUNE_CELL_MIET Run native, sliding-2x2, and sliding-4x4 MIET-FLIM.
dataRoot = 'E:\Luminosa_data\260813\RT_Jurkat_CD58_memglow_20260813_1';
ptuFile = fullfile(dataRoot, '_20260813-160712', 'RawImage.ptu');

cfg = struct();
cfg.excitationPulseIndex = 2; % Confirmed/adjustable PIE pulse assigned to 640 nm.
cfg.excitationNm = 640;
cfg.ismWavelengthNm = 690;   % Red emission wavelength used by ACO-ISM.
cfg.minPhotonsPerPixel = 3;  % Permissive support for the preliminary mean image.
cfg.lifetimeRangeNs = [0.5 1.8];
cfg.showFigure = true;
cfg.saveOutputs = true;
cfg.useGPU = false;
cfg.bayesMinPhotons = 10;
cfg.fixSlbAmplitude = true;
cfg.slbAmplitudeScale = 1;
cfg.maxSlbClippedFraction = 0.10;
cfg.requireValidSegmentation = true;
cfg.componentMaps = struct( ...
    'enabled', true, ...
    'posteriorThreshold', [0.8 0.95], ...
    'minExpectedPhotons', [10 10], ...
    'probabilityContourLevels', [0.5 0.7 0.9]);
% Bayesian grid, sized from study_flim_grid_density_sweep.
%
% membraneTauCount was 10 (the immune_cell_MIET default). At the ~1e4 photons a
% 4x4 window carries, that grid gave a 51% false three-component rate on
% simulated BIexponential data: an off-grid single exponential is fit better by
% two on-grid exponentials than by one, and enough photons make that decisive.
% 48 points takes it to 0.2% for ~5 points of detection power. 32 points is
% enough for a typical window but leaves ~18% at 3e4 photons, and since MIET
% brightness tracks emitter height that residual would be height-dependent -
% so the grid is sized for the brightest windows, not the median.
%
% The bounds are set explicitly too. The default lower bound is
% max(1.15*tauSlb, tauSlb + 2*dt, 0.05), about 0.62 ns for a 0.3 ns SLB at
% 0.16 ns bins, which cannot represent a membrane component below that at all.
%
% slbCountPriorNodes marginalises the fixed SLB count over its calibration
% uncertainty rather than imposing it; on a fine grid that cut SLB-induced
% lifetime bias by 56%, and on a coarse grid it does nothing.
% The BOUNDS are deliberately left unset. flim_bayes_fixed_slb derives them
% from the fitted SLB lifetime as
%   [max(1.15*tauSlb, tauSlb + 2*dt, 0.05), min(0.8*period, max(5, 4*tauSlb))]
% which for a fitted tauSlb of 0.358 ns at 0.16 ns bins gives a lower bound of
% 0.678 ns. That guard keeps membrane states at least two TCSPC bins away from
% the SLB. Forcing a lower bound (an earlier version used 0.4 ns) puts grid
% states within two bins of the SLB, where they are nearly degenerate with it -
% and because the SLB amplitude is fixed, such a state acts as a spurious extra
% amplitude degree of freedom. It is also unphysical for MIET, where the SLB is
% the most quenched layer so membrane lifetimes must be longer.
cfg.bayes = struct('batchSize', 2048, 'includeBackground', true, ...
    'signalGrid', [0.25 0.5 0.75 1], 'membraneTauCount', 48, ...
    'fractionStep', 0.2, 'minimumMembraneFraction', 0.1, ...
    'slbCountRelTol', 0.0025, 'slbCountPriorNodes', 5);
cfg.spatialBinning = struct('enabled', true, ...
    'binSize', [2 2], 'step', [1 1]);
cfg.spatialBinning4x4 = struct('enabled', true, ...
    'binSize', [4 4], 'step', [1 1]);
cfg.segmentation = struct( ...
    'smoothSigma', 2.0, ...
    'minLifetimeContrastNs', 0.05, ...
    'cellSeparationSigma', 1.5, ...
    'growthMinLifetimeContrastNs', 0.025, ...
    'growthSeparationSigma', 0.75, ...
    'slbLowPopulationQuantile', 0.45, ...
    'minPlausibleCellFraction', 0.005, ...
    'maxCellComponents', 1, ...
    'fallbackUseIntensity', false, ...
    'minCellArea', 500, ...
    'minCellCoreArea', 20, ...
    'fallbackMinContrastNs', 0.025, ...
    'fallbackCloseRadius', 7, ...
    'fallbackMinArea', 250);

result = immune_cell_MIET(ptuFile, cfg);
