function out = run_immune_cell_MIET_biexp_slb(dataRoot, opts)
%RUN_IMMUNE_CELL_MIET_BIEXP_SLB Soft-SLB biexponential over a whole session.
%
% out = run_immune_cell_MIET_biexp_slb()
% out = run_immune_cell_MIET_biexp_slb(dataRoot, opts)
%
% Finds every saved analysis below dataRoot that carries a per-pixel TCSPC cube
% and refits it with the two-component soft-SLB model, writing each result into a
% NEW folder beside that analysis. Nothing existing is overwritten: the
% three-model output stays exactly where it is, so the two can be compared.

    if nargin < 1 || isempty(dataRoot)
        dataRoot = ['D:\Luminosa\Data\260813\' ...
            'RT_Jurkat_CD58_memglow_20260813_1'];
    end
    if nargin < 2 || isempty(opts); opts = struct(); end

    found = dir(fullfile(dataRoot, '**', ...
        'immune_cell_MIET_640nm_red_analysis.mat'));
    if isempty(found)
        error('run_immune_cell_MIET_biexp_slb:NoAnalyses', ...
            'No analysis MAT below %s', dataRoot);
    end
    paths = sort(arrayfun(@(f) fullfile(f.folder, f.name), found, ...
        'UniformOutput', false));
    fprintf('run_immune_cell_MIET_biexp_slb: %d analysis MAT(s) below\n  %s\n', ...
        numel(paths), dataRoot);

    rows = struct([]);
    results = cell(numel(paths), 1);
    for k = 1:numel(paths)
        [folder, ~] = fileparts(paths{k});
        try
            result = immune_cell_MIET_biexp_slb(paths{k}, opts);
            results{k} = result;
            valid = isfinite(result.maps.tau1Ns);
            entry = struct('analysisMat', paths{k}, 'outputDir', ...
                result.opts.outputDir, 'pixelsFitted', nnz(valid), ...
                'tau1MedianNs', median(result.maps.tau1Ns(valid)), ...
                'tau2MedianNs', median(result.maps.tau2Ns(valid)), ...
                'photonShare2Median', ...
                    median(result.maps.photonFraction2(valid)), ...
                'priorPinnedFraction', ...
                    mean(abs(result.maps.slbPullSigma(valid)) > 1.8), ...
                'reducedDevianceMedian', ...
                    median(result.maps.reducedDeviance(valid)), ...
                'status', 'ok');
        catch runError
            fprintf('\n  FAILED on %s\n    %s\n', folder, runError.message);
            entry = struct('analysisMat', paths{k}, 'outputDir', '', ...
                'pixelsFitted', 0, 'tau1MedianNs', NaN, ...
                'tau2MedianNs', NaN, 'photonShare2Median', NaN, ...
                'priorPinnedFraction', NaN, ...
                'reducedDevianceMedian', NaN, ...
                'status', runError.identifier);
        end
        if isempty(rows); rows = entry; else; rows(end + 1) = entry; end %#ok<AGROW>
    end

    summary = struct2table(rows);
    csvFile = fullfile(dataRoot, 'biexp_slb_session_summary.csv');
    writetable(summary, csvFile);

    fprintf('\n=============================================================\n');
    fprintf('SESSION SUMMARY: soft-SLB biexponential\n\n');
    fprintf(['  pixels    tau1(ns)  tau2(ns)  share2  pinned  redDev   ' ...
        'analysis\n']);
    fprintf(['  ---------------------------------------------------------' ...
        '-----------\n']);
    for k = 1:height(summary)
        [~, acq] = fileparts(fileparts(fileparts(summary.analysisMat{k})));
        fprintf('  %7d  %8.4f  %8.3f  %6.3f  %6.2f  %6.3f   %s\n', ...
            summary.pixelsFitted(k), summary.tau1MedianNs(k), ...
            summary.tau2MedianNs(k), summary.photonShare2Median(k), ...
            summary.priorPinnedFraction(k), ...
            summary.reducedDevianceMedian(k), acq);
    end
    fprintf('\n  wrote %s\n', csvFile);
    out = struct('summary', summary, 'results', {results}, ...
        'dataRoot', dataRoot, 'csvFile', csvFile);
end
