%RUN_BATCH_IMMUNE_CELL_MIET Analyze all suitable cell acquisitions in a folder.
dataRoot = 'E:\Luminosa_data\260813\RT_Jurkat_CD58_memglow_20260813_1';

cfg = struct();
cfg.scanPlanes = {'XY'};          % Cross-sections are catalogued, not fitted.
cfg.minDwellMs = 0.4;             % Excludes fast overview/test scans.
cfg.minCompletionFraction = 0.95; % Excludes interrupted raster scans.
cfg.minRecords = 1e6;
cfg.resume = true;                % Reuse valid per-acquisition MAT results.
cfg.overwrite = false;
cfg.dryRun = false;               % Set true for a fast header-only audit.
cfg.continueOnError = true;
cfg.showFigures = false;          % PNG figures are still saved.
cfg.saveTcspcPix = true;          % Detector-summed, reassigned uint16 cube.
cfg.qc = struct('maxSlbClippedFraction', 0.10);

pipelineCfg = struct();
pipelineCfg.excitationPulseIndex = 2;
pipelineCfg.excitationNm = 640;
pipelineCfg.ismWavelengthNm = 690;
pipelineCfg.tcspcBinNs = 0.16;    % Exact multiple of both 40-ps and 20-ps data.
pipelineCfg.minPhotonsPerPixel = 3;
pipelineCfg.lifetimeRangeNs = [0.5 1.8];
pipelineCfg.showWaitbar = false;
pipelineCfg.useGPU = true;        % Quadro T1000 4 GB; Bayesian path falls back to CPU on failure.
pipelineCfg.bayesMinPhotons = 10;
pipelineCfg.fixSlbAmplitude = true;
pipelineCfg.slbAmplitudeScale = 1;
pipelineCfg.maxSlbClippedFraction = 0.10;
pipelineCfg.requireValidSegmentation = true;
pipelineCfg.componentMaps = struct( ...
    'enabled', true, ...
    'posteriorThreshold', [0.8 0.95], ...
    'minExpectedPhotons', [10 10], ...
    'probabilityContourLevels', [0.5 0.7 0.9]);
% mergeStruct is shallow, so the whole bayes struct must be restated here.
pipelineCfg.bayes = struct('batchSize', 2048, 'includeBackground', true, ...
    'signalGrid', [0.25 0.5 0.75 1], 'membraneTauCount', 10, ...
    'fractionStep', 0.2, 'minimumMembraneFraction', 0.1, ...
    'slbCountRelTol', 0.02);
pipelineCfg.spatialBinning = struct('enabled', true, ...
    'binSize', [2 2], 'step', [1 1]);
pipelineCfg.spatialBinning4x4 = struct('enabled', true, ...
    'binSize', [4 4], 'step', [1 1]);
pipelineCfg.segmentation = struct( ...
    'smoothSigma', 2.0, ...
    'minLifetimeContrastNs', 0.05, ...
    'cellSeparationSigma', 1.5, ...
    'growthMinLifetimeContrastNs', 0.025, ...
    'growthSeparationSigma', 0.75, ...
    'slbLowPopulationQuantile', 0.45, ...
    'minPlausibleCellFraction', 0.005, ...
    'maxCellComponents', 1, ...
    'fallbackUseIntensity', false, ...
    'minCellArea', 500, ...
    'minCellCoreArea', 20, ...
    'fallbackMinContrastNs', 0.025, ...
    'fallbackCloseRadius', 7, ...
    'fallbackMinArea', 250);
cfg.pipeline = pipelineCfg;

[summary, batchInfo] = batch_immune_cell_MIET(dataRoot, cfg);
