%RUN_IMMUNE_CELL_MIET Run native, sliding-2x2, and sliding-4x4 MIET-FLIM.
dataRoot = 'E:\Luminosa_data\260813\RT_Jurkat_CD58_memglow_20260813_1';
ptuFile = fullfile(dataRoot, '_20260813-160712', 'RawImage.ptu');

cfg = struct();
cfg.excitationPulseIndex = 2; % Confirmed/adjustable PIE pulse assigned to 640 nm.
cfg.excitationNm = 640;
cfg.ismWavelengthNm = 690;   % Red emission wavelength used by ACO-ISM.
cfg.minPhotonsPerPixel = 3;  % Permissive support for the preliminary mean image.
cfg.lifetimeRangeNs = [0.5 1.8];
cfg.showFigure = true;
cfg.saveOutputs = true;
cfg.useGPU = false;
cfg.bayesMinPhotons = 10;
cfg.fixSlbAmplitude = true;
cfg.slbAmplitudeScale = 1;
cfg.maxSlbClippedFraction = 0.10;
cfg.requireValidSegmentation = true;
cfg.componentMaps = struct( ...
    'enabled', true, ...
    'posteriorThreshold', [0.8 0.95], ...
    'minExpectedPhotons', [10 10], ...
    'probabilityContourLevels', [0.5 0.7 0.9]);
cfg.spatialBinning = struct('enabled', true, ...
    'binSize', [2 2], 'step', [1 1]);
cfg.spatialBinning4x4 = struct('enabled', true, ...
    'binSize', [4 4], 'step', [1 1]);
cfg.segmentation = struct( ...
    'smoothSigma', 2.0, ...
    'minLifetimeContrastNs', 0.05, ...
    'cellSeparationSigma', 1.5, ...
    'growthMinLifetimeContrastNs', 0.025, ...
    'growthSeparationSigma', 0.75, ...
    'slbLowPopulationQuantile', 0.45, ...
    'minPlausibleCellFraction', 0.005, ...
    'maxCellComponents', 1, ...
    'fallbackUseIntensity', false, ...
    'minCellArea', 500, ...
    'minCellCoreArea', 20, ...
    'fallbackMinContrastNs', 0.025, ...
    'fallbackCloseRadius', 7, ...
    'fallbackMinArea', 250);

result = immune_cell_MIET(ptuFile, cfg);
