function out = run_free_dye_lifetime_above_surface(dataRoot, opts)
%RUN_FREE_DYE_LIFETIME_ABOVE_SURFACE tau0 from every XZ/YZ scan in a session.
%
% out = run_free_dye_lifetime_above_surface()
% out = run_free_dye_lifetime_above_surface(dataRoot, opts)
%
% Runs fit_free_dye_lifetime_above_surface on every non-XY acquisition below
% dataRoot and combines the answers. Each scan gets its own mean-FLIM image and
% fitted-TCSPC figure in <acquisition>/free_dye_above_surface/.
%
% The five cross-sections in the 260813 session were taken across an hour on
% different cells, so BETWEEN-SCAN agreement is the test that matters: it
% separates a property of the dye from a property of one field of view. That
% spread is reported next to the within-scan spread over tail starts, because
% the two fail for different reasons - within-scan drift means a contaminated
% tail, between-scan scatter means real heterogeneity.

    if nargin < 1 || isempty(dataRoot)
        dataRoot = ['D:\Luminosa\Data\260813\' ...
            'RT_Jurkat_CD58_memglow_20260813_1'];
    end
    if nargin < 2 || isempty(opts); opts = struct(); end
    if ~isfield(opts, 'outputRoot') || isempty(opts.outputRoot)
        opts.outputRoot = fullfile(dataRoot, 'free_dye_above_surface');
    end
    if ~isfolder(opts.outputRoot); mkdir(opts.outputRoot); end

    files = dir(fullfile(dataRoot, '**', 'RawImage.ptu'));
    if isempty(files)
        error('run_free_dye_lifetime_above_surface:NoFiles', ...
            'No RawImage.ptu below %s', dataRoot);
    end
    paths = sort(arrayfun(@(f) fullfile(f.folder, f.name), files, ...
        'UniformOutput', false));

    fprintf('run_free_dye_lifetime_above_surface: screening %d PTU file(s)\n', ...
        numel(paths));
    crossSections = {};
    planes = {};
    for k = 1:numel(paths)
        try
            head = PTU_Read_Head(paths{k});
        catch headError
            fprintf('  skip (header failed, %s): %s\n', ...
                headError.identifier, paths{k});
            continue;
        end
        if ~isfield(head, 'ImgHdr_ScanDirection'); continue; end
        switch double(head.ImgHdr_ScanDirection)
            case 1; plane = 'YZ';
            case 2; plane = 'XZ';
            otherwise; continue;
        end
        crossSections{end + 1} = paths{k}; %#ok<AGROW>
        planes{end + 1} = plane; %#ok<AGROW>
    end
    fprintf('  %d cross-section(s) found\n', numel(crossSections));
    if isempty(crossSections)
        error('run_free_dye_lifetime_above_surface:NoCrossSections', ...
            'No XZ or YZ acquisitions below %s', dataRoot);
    end

    rows = struct([]);
    results = cell(numel(crossSections), 1);
    for k = 1:numel(crossSections)
        [folder, ~] = fileparts(crossSections{k});
        [~, acquisition] = fileparts(folder);
        localOpts = opts;
        localOpts.outputDir = fullfile(folder, 'free_dye_above_surface');
        try
            result = fit_free_dye_lifetime_above_surface( ...
                crossSections{k}, localOpts);
            results{k} = result;
            entry = struct('acquisition', acquisition, 'plane', planes{k}, ...
                'axialAxis', result.axial.name, ...
                'surfaceRow', result.surfaceIndex, ...
                'topDistancePix', result.selection.topDistancePix, ...
                'awayDirection', result.direction.name, ...
                'arrivalGainNs', result.direction.arrivalGainNs, ...
                'selectedPixels', result.selection.pixelCount, ...
                'selectedPhotons', result.selection.photons, ...
                'backgroundFraction', result.selection.backgroundFraction, ...
                'meanLifetimeNs', result.fit.meanLifetimeNs, ...
                'correctedMeanNs', result.fit.correctedMeanNs, ...
                'logLinearNs', result.fit.logLinearMedianNs, ...
                'logLinearSpreadNs', result.fit.logLinearSpreadNs, ...
                'tau0Ns', result.fit.tau0Ns, ...
                'tailSpreadNs', result.fit.tailSpreadNs, ...
                'nDistComponents', numel(result.fit.distTauNs), ...
                'distShortNs', firstOrNaN(result.fit.distTauNs), ...
                'distLongNs', lastOrNaN(result.fit.distTauNs), ...
                'distLongPhotonShare', lastOrNaN(result.fit.distPhotonShare), ...
                'distMeanNs', result.fit.distMeanNs, ...
                'pedestalCounts', result.fit.pedestal.level, ...
                'signalEndNs', result.fit.pedestal.signalEnd * result.dtNs, ...
                'irfTauNs', firstOrNaN(result.fit.irfTauNs), ...
                'status', 'ok');
        catch runError
            fprintf('\n  FAILED on %s: %s\n', acquisition, runError.message);
            entry = struct('acquisition', acquisition, 'plane', planes{k}, ...
                'axialAxis', '', 'surfaceRow', NaN, 'topDistancePix', NaN, ...
                'awayDirection', '', 'arrivalGainNs', NaN, ...
                'selectedPixels', 0, 'selectedPhotons', 0, ...
                'backgroundFraction', NaN, 'meanLifetimeNs', NaN, ...
                'correctedMeanNs', NaN, 'logLinearNs', NaN, ...
                'logLinearSpreadNs', NaN, ...
                'tau0Ns', NaN, 'tailSpreadNs', NaN, ...
                'nDistComponents', 0, 'distShortNs', NaN, ...
                'distLongNs', NaN, 'distLongPhotonShare', NaN, ...
                'distMeanNs', NaN, 'pedestalCounts', NaN, ...
                'signalEndNs', NaN, 'irfTauNs', NaN, ...
                'status', shortReason(runError));
        end
        if isempty(rows); rows = entry; else; rows(end + 1) = entry; end %#ok<AGROW>
    end

    summary = struct2table(rows);
    csvFile = fullfile(opts.outputRoot, 'free_dye_above_surface_summary.csv');
    writetable(summary, csvFile);

    fprintf('\n=============================================================\n');
    fprintf('SUMMARY: unquenched lifetime above the surface\n\n');
    fprintf(['  acquisition        plane  photons   mean(ns)  mono(ns) ' ...
        'spread  dist components (photon share)\n']);
    fprintf(['  ------------------------------------------------------' ...
        '--------------------------------------\n']);
    for k = 1:height(summary)
        if summary.nDistComponents(k) > 0
            % DistTailfit solves on a discrete rate grid, so one true
            % lifetime routinely splits across neighbouring grid points. The
            % photon-weighted MEAN is the estimate; the individual components
            % are grid structure and must not be read as populations.
            distText = sprintf('mean %.3f ns over %d grid components', ...
                summary.distMeanNs(k), summary.nDistComponents(k));
        else
            distText = '-';
        end
        fprintf('  %-18s %-5s  %8.3g  %8s  %8s %6s  %s\n', ...
            summary.acquisition{k}, summary.plane{k}, ...
            summary.selectedPhotons(k), ...
            num(summary.meanLifetimeNs(k)), num(summary.tau0Ns(k)), ...
            num(summary.tailSpreadNs(k)), distText);
    end

    out = struct('summary', summary, 'results', {results}, ...
        'dataRoot', dataRoot, 'opts', opts, ...
        'combinedTau0Ns', NaN, 'betweenScanSdNs', NaN, ...
        'combinedMonoNs', NaN, 'combinedDistMeanNs', NaN, ...
        'combinedCorrectedNs', NaN, 'combinedLogLinearNs', NaN, ...
        'tau0RangeNs', [NaN NaN], ...
        'medianTailSpreadNs', NaN);
    usable = isfinite(summary.meanLifetimeNs) & summary.selectedPhotons > 0;
    if any(usable)
        % The MODEL-FREE mean lifetime is combined, not the mono-exponential
        % fit: the mono fit drifts by 1.7-2.0 ns depending on where its tail
        % starts, so averaging it would average an artefact of the window.
        values = summary.meanLifetimeNs(usable);
        weights = summary.selectedPhotons(usable);
        weights = weights / sum(weights);
        out.combinedTau0Ns = sum(weights .* values);
        out.betweenScanSdNs = std(values);
        out.combinedMonoNs = sum(weights .* summary.tau0Ns(usable));
        % omitnan: one scan's distribution fit can fail without voiding the rest
        out.combinedDistMeanNs = mean(summary.distMeanNs(usable), 'omitnan');
        out.combinedCorrectedNs = mean(summary.correctedMeanNs(usable), 'omitnan');
        out.combinedLogLinearNs = mean(summary.logLinearNs(usable), 'omitnan');
        estimates = [out.combinedCorrectedNs, out.combinedMonoNs, ...
            out.combinedDistMeanNs, out.combinedLogLinearNs];
        labels = {'truncation-corrected first moment', ...
            'mono-exponential tail fit', 'lifetime distribution', ...
            'log-linear regression'};
        fprintf('\n  FOUR ESTIMATORS OF tau0, combined over the usable scans:\n');
        for e = 1:numel(estimates)
            fprintf('      %-36s %s ns\n', labels{e}, num(estimates(e)));
        end
        finite = estimates(isfinite(estimates));
        if ~isempty(finite)
            out.tau0RangeNs = [min(finite) max(finite)];
            fprintf(['\n  tau0 lies in %.2f - %.2f ns. The spread BETWEEN ' ...
                'estimators, not the\n  between-scan sd of %.3f ns, is the ' ...
                'real uncertainty: the five scans agree\n  closely with ' ...
                'each other, but the decay is not perfectly ' ...
                'single-exponential.\n  %.1f ns of decay is fitted, about ' ...
                '%.1f lifetimes.\n'], ...
                out.tau0RangeNs(1), out.tau0RangeNs(2), ...
                out.betweenScanSdNs, median(summary.signalEndNs(usable)), ...
                median(summary.signalEndNs(usable)) / out.combinedCorrectedNs);
            % Quote the ACTUAL truncation bias rather than a remembered one.
            % With the whole period stored the window is ~9 lifetimes and the
            % correction is negligible; it was ~0.5 ns only while the reader
            % silently stored 30.7 ns of the 50 ns period.
            biasNs = out.combinedCorrectedNs - out.combinedTau0Ns;
            fprintf(['  Raw first moment %.3f ns, corrected %.3f ns: the ' ...
                'truncation bias is only\n  %.3f ns here, because the ' ...
                'window is %.1f lifetimes. It was ~0.5 ns while the reader\n' ...
                '  stored only part of the period.\n'], ...
                out.combinedTau0Ns, out.combinedCorrectedNs, biasNs, ...
                median(summary.signalEndNs(usable)) / out.combinedCorrectedNs);
        end
        out.medianTailSpreadNs = median(summary.tailSpreadNs(usable), ...
            'omitnan');
        fprintf(['\n  combined tau0 = %.3f ns over %d scan(s), ' ...
            'photon-weighted\n'], out.combinedTau0Ns, nnz(usable));
        fprintf('      between-scan sd  %.3f ns\n', out.betweenScanSdNs);
        fprintf('      within-scan spread over tail starts, median %.3f ns\n', ...
            out.medianTailSpreadNs);
        if out.betweenScanSdNs > 3 * max(out.medianTailSpreadNs, 0.01)
            fprintf(['      Between-scan scatter exceeds the within-scan ' ...
                'drift, so the difference is\n      real heterogeneity ' ...
                'between fields of view rather than fitting noise.\n']);
        else
            fprintf(['      The two spreads are comparable, so the scans ' ...
                'agree to within their own\n      fitting uncertainty.\n']);
        end

        fprintf(['\n  Against the calibration on disk: calibrationCurve.mat ' ...
            'spans 0.865-3.362 ns\n  over 0.1-30 nm. A measured tau0 of ' ...
            '%.3f ns is the asymptote that curve must\n  approach.\n'], ...
            out.combinedTau0Ns);
        if out.combinedTau0Ns <= 3.362
            fprintf(['  Since %.3f ns is NOT above the curve''s ceiling, ' ...
                'the 3.30 ns pool cannot be\n  hundreds of nm up on this ' ...
                'calibration - it would sit near the surface, and the\n' ...
                '  "internalised" reading needs independent support such ' ...
                'as the ring test.\n'], out.combinedTau0Ns);
        else
            fprintf(['  Since %.3f ns EXCEEDS the curve''s 3.362 ns ' ...
                'ceiling, that curve is merely\n  truncated, and ' ...
                'regenerating it out to several hundred nm is the fix.\n'], ...
                out.combinedTau0Ns);
        end
    end

    matFile = fullfile(opts.outputRoot, 'free_dye_above_surface_summary.mat');
    save(matFile, 'out', '-v7.3');
    fprintf('\n  wrote %s\n  wrote %s\n', csvFile, matFile);
end

function value = firstOrNaN(values)
    if isempty(values) || all(isnan(values)); value = NaN; else
        value = double(values(1));
    end
end

function value = lastOrNaN(values)
    if isempty(values) || all(isnan(values)); value = NaN; else
        value = double(values(end));
    end
end

function text = num(value)
    if isnan(value); text = '-'; else; text = sprintf('%.3f', value); end
end

function text = shortReason(err)
    parts = strsplit(err.identifier, ':');
    text = parts{end};
    if isempty(text); text = 'failed'; end
end
