function [ok, exponentialCount, tauNs, tauMeanNs, coefficients, ...
        speciesFraction, fitCounts, metrics, messages] = fitRegions( ...
        curves, regionName, irf, dtNs, maximumExponentials, oneStateSeed, ...
        twoStateSeed, lifetimeBounds, includeBackground, minimumPhotons, ...
        maximumIterations, requiredBicImprovement, minimumSeparationFraction, ...
        minimumAmplitudeFraction)
%FITREGIONS Apply model selection independently to every curve column.

    regionCount = size(curves, 2);
    binCount = size(curves, 1);
    ok = false(regionCount, 1);
    exponentialCount = zeros(regionCount, 1);
    tauNs = nan(regionCount, 2);
    tauMeanNs = nan(regionCount, 1);
    coefficients = zeros(regionCount, 3);
    speciesFraction = nan(regionCount, 2);
    fitCounts = zeros(binCount, regionCount);
    metrics = nan(regionCount, 8);
    messages = cell(regionCount, 1);

    for region = 1:regionCount
        fprintf('Fitting %s %d/%d (%d B12 photons)...\n', regionName, ...
            region, regionCount, round(sum(curves(:, region))));
        [ok(region), exponentialCount(region), tauNs(region, :), ...
            tauMeanNs(region), coefficients(region, :), speciesFraction(region, :), ...
            fitCounts(:, region), metrics(region, :), messages{region}] = ...
            selectModel(curves(:, region), irf, dtNs, maximumExponentials, ...
            oneStateSeed, twoStateSeed, lifetimeBounds, includeBackground, ...
            minimumPhotons, maximumIterations, requiredBicImprovement, ...
            minimumSeparationFraction, minimumAmplitudeFraction);
    end
end
